### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ymmshi** [ITJesse/NeteaseMusicPlugin#3]
Dear ITJesse,
      First,thanks for your great contribution on this project! But when I download and build this project on my Mac,the different errors occur,such as permission denied,insert_dylib not found...can u offer a detail tutorial or can u help me and I am pleased to sort out the documents.
Regards
meiyouren

**Comment by ITJesse** [comment]
You should find the insert_dylib project and build it yourself.
Maybe you should also modify the build script to fit your situation.

**Comment by ymmshi** [comment]
Thanks for your solutions,i built it successfully yesterday. But I got a new problem as the UnblockNeteaseMusic project's issues #18.Maybe the api of netease music changed. Look forward to your update！
